apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-dba-pg-tools-db
  namespace: dba-pg-tools
spec:
  concurrencyPolicy: Forbid
  schedule: '57 23 * * *'
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: restart-dba-pg-tools-db
          restartPolicy: Never
          containers:
            - name: restart-dba-pg-tools-cron
              image: raspbernetes/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/dba-pg-tools-db'
