apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-dba-pg-tools-db
  namespace: dba-pg-tools
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["dba-pg-tools-db"]
    verbs: ["get", "patch"]
