apiVersion: batch/v1 
kind: CronJob 
metadata:   
  name: database-core-job-bloat
  namespace: dba-pg-tools
spec:
  jobTemplate:
     
    spec:
      ttlSecondsAfterFinished: 600
      template:     
          
        spec:       
          
          containers:
          - name: dba-pg-tools
            image: dlpco/postgres-py-automator
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            env:
              - name: POSTGRES_MAIN_DB
                valueFrom:
                  secretKeyRef:
                    name: db-core
                    key: DATABASE_NAME
              - name: POSTGRES_MAIN_USER
                valueFrom:
                  secretKeyRef:
                    name: db-core
                    key: DATABASE_USER
              - name: POSTGRES_MAIN_HOST
                valueFrom:
                  secretKeyRef:
                    name: db-core
                    key: DATABASE_HOST
              - name: POSTGRES_MAIN_PORT
                valueFrom:
                  secretKeyRef:
                    name: db-core
                    key: DATABASE_PORT
              - name: POSTGRES_MAIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-core
                    key: DATABASE_PASSWORD

              - name: POSTGRES_K8S_DB
                valueFrom:
                  secretKeyRef:
                    name: db-k8s-pg-tools
                    key: DATABASE_NAME
              - name: POSTGRES_K8S_USER
                valueFrom:
                  secretKeyRef:
                    name: db-k8s-pg-tools
                    key: DATABASE_USER
              - name: POSTGRES_K8S_HOST
                valueFrom:
                  secretKeyRef:
                    name: db-k8s-pg-tools
                    key: DATABASE_HOST
              - name: POSTGRES_K8S_PORT
                valueFrom:
                  secretKeyRef:
                    name: db-k8s-pg-tools
                    key: DATABASE_PORT
              - name: POSTGRES_K8S_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-k8s-pg-tools
                    key: DATABASE_PASSWORD
            command: ["python3"]
            args: ["get_bloat_tables.py", "public", "all"]
          restartPolicy: Never
  schedule: "0 15 * * *"
 