apiVersion: apps/v1
kind: Deployment
metadata:
  name: dba-pg-tools-db
  namespace: dba-pg-tools
  labels:
    app: db-k8s-pg-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dba-pg-tools
  template:
    metadata:
      labels:
        app: dba-pg-tools
    spec:
      containers:
      - name: dba-pg-tools
        image: dlpco/postgres-fully-extension:14.4
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_NAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_USERNAME
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_HOST
