apiVersion: apps/v1
kind: Deployment
metadata:
  name: dba-pg-tools-worker
  namespace: dba-pg-tools
  labels:
    app: dba-pg-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dba-pg-tools
  template:
    metadata:
      labels:
        app: dba-pg-tools
    spec:
      containers:
      - name: dba-pg-tools
        image: dlpco/postgres-py-automator
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_MAIN_DB
            valueFrom:
              secretKeyRef:
                name: db-slc-dispatcher
                key: DATABASE_NAME
          - name: POSTGRES_MAIN_USER
            valueFrom:
              secretKeyRef:
                name: db-slc-dispatcher
                key: DATABASE_USER
          - name: POSTGRES_MAIN_HOST
            valueFrom:
              secretKeyRef:
                name: db-slc-dispatcher
                key: DATABASE_HOST
          - name: POSTGRES_MAIN_PORT
            valueFrom:
              secretKeyRef:
                name: db-slc-dispatcher
                key: DATABASE_PORT
          - name: POSTGRES_MAIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-slc-dispatcher
                key: DATABASE_PASSWORD

          - name: POSTGRES_K8S_DB
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_NAME
          - name: POSTGRES_K8S_USER
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_USER
          - name: POSTGRES_K8S_HOST
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_HOST
          - name: POSTGRES_K8S_PORT
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_PORT
          - name: POSTGRES_K8S_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-k8s-pg-tools
                key: DATABASE_PASSWORD
        command: ["python3"]
        args: ["sleep.py"]